name: Setup action for CI and CD workflows
description: A setup action for CI and CD jobs in the P5-wrapper organisation

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      name: Checkout the latest code for the current PR

    - uses: actions/setup-node@v4
      name: Setup node
      with:
        node-version: latest

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      shell: bash

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
